-- Spacely / CINEXTMA Supabase SQL Editor setup
-- Target: Supabase PostgreSQL
-- Safe to run against a fresh database. The policy section is also safe to re-run.
-- Run this in Supabase Dashboard -> SQL Editor.

begin;

-- ============================================================
-- 1. Tables
-- ============================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  created_at timestamptz default now()
);

create table if not exists public.watchlist (
  user_id uuid not null references auth.users(id) on delete cascade,
  id integer not null,
  type text not null,
  adult boolean not null,
  backdrop_path text,
  poster_path text,
  release_date date not null,
  title text not null,
  vote_average numeric(4,1) not null,
  created_at timestamptz not null default now(),
  constraint watchlist_pkey primary key (user_id, id, type),
  constraint watchlist_type_check check (type in ('movie', 'tv'))
);

create table if not exists public.histories (
  user_id uuid not null references auth.users(id) on delete cascade,
  id bigint generated by default as identity primary key,
  media_id integer not null,
  type text not null,
  season integer not null default 0,
  episode integer not null default 0,
  duration double precision not null default 0,
  last_position double precision not null default 0,
  completed boolean not null default false,
  adult boolean not null,
  backdrop_path text,
  poster_path text,
  release_date date not null,
  title text not null,
  vote_average numeric(4,1) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint histories_type_check check (type in ('movie', 'tv')),
  constraint histories_user_media_episode_key
    unique (user_id, media_id, type, season, episode)
);

-- Useful query indexes.
create unique index if not exists profiles_username_key
  on public.profiles (username);

create index if not exists histories_user_updated_idx
  on public.histories (user_id, updated_at desc);

-- ============================================================
-- 2. Updated-at trigger
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at on public.histories;

create trigger set_updated_at
before update on public.histories
for each row
execute function public.set_updated_at();

-- ============================================================
-- 3. Row Level Security
-- ============================================================

alter table public.profiles enable row level security;
alter table public.watchlist enable row level security;
alter table public.histories enable row level security;

-- Remove policies created by earlier versions so this block is deterministic.
drop policy if exists "Enable read access for all users" on public.profiles;
drop policy if exists "Users can insert their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
drop policy if exists "Users can delete their own profile" on public.profiles;

drop policy if exists "Users can view their own watchlist" on public.watchlist;
drop policy if exists "Users can insert their own watchlist" on public.watchlist;
drop policy if exists "Users can delete their own watchlist" on public.watchlist;
drop policy if exists "Users can update their own watchlist" on public.watchlist;

drop policy if exists "Users can view their own histories" on public.histories;
drop policy if exists "Users can insert their own histories" on public.histories;
drop policy if exists "Users can update their own histories" on public.histories;
drop policy if exists "Users can delete their own histories" on public.histories;

-- Profiles: usernames are public, but users may only modify their own row.
create policy "Profiles are publicly readable"
on public.profiles
for select
to anon, authenticated
using (true);

create policy "Users can insert their own profile"
on public.profiles
for insert
to authenticated
with check ((select auth.uid()) = id);

create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "Users can delete their own profile"
on public.profiles
for delete
to authenticated
using ((select auth.uid()) = id);

-- Watchlist: private to the authenticated owner.
create policy "Users can view their own watchlist"
on public.watchlist
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own watchlist"
on public.watchlist
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own watchlist"
on public.watchlist
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own watchlist"
on public.watchlist
for delete
to authenticated
using ((select auth.uid()) = user_id);

-- History: private to the authenticated owner.
create policy "Users can view their own histories"
on public.histories
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own histories"
on public.histories
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own histories"
on public.histories
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own histories"
on public.histories
for delete
to authenticated
using ((select auth.uid()) = user_id);

-- ============================================================
-- 4. Grants
-- ============================================================
-- The app uses the public/publishable Supabase key, so access is
-- controlled by RLS. No service-role key belongs in browser code.

grant usage on schema public to anon, authenticated;

grant select on public.profiles to anon, authenticated;
grant insert, update, delete on public.profiles to authenticated;

grant select, insert, update, delete on public.watchlist to authenticated;
grant select, insert, update, delete on public.histories to authenticated;

-- Keep identity-sequence access available for history inserts.
grant usage, select on sequence public.histories_id_seq to authenticated;

commit;

-- ============================================================
-- Verification queries (run separately if desired)
-- ============================================================
-- select table_name from information_schema.tables
-- where table_schema = 'public'
-- order by table_name;
--
-- select schemaname, tablename, policyname, cmd
-- from pg_policies
-- where schemaname = 'public'
-- order by tablename, policyname;
